{% set name = "cli_helpers" %}
{% set version = "2.6.0" %}
{% set sha256 = "1d37659ebb4eb5e2ebecd8a148ba2698eb7da62b34d63124bf5ce7ff3c4d413f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - configobj >=5.0.5
    - pygments >=1.6
    - tabulate >=0.9.0
    - wcwidth

test:
  imports:
    - cli_helpers
    - cli_helpers.tabular_output
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://cli-helpers.rtfd.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python helpers for common CLI tasks
  doc_url: http://cli-helpers.rtfd.io
  dev_url: https://github.com/dbcli/cli_helpers

extra:
  recipe-maintainers:
    - dhirschfeld
    - mariusvniekerk
